#intégration continue à nouveau commit poussé sur notre dépôt
language: php

sudo: true

script: 
  - ./git-ftp push -u "barnabe.geffroy" -p $PASSWORD "sftp://pedago-ext.ensiie.fr/~/public_html/projet-web"

notifications:
  email:
    recipients:
      - barnabe.geffroy@ecomail.fr
    on_success: never 
    on_failure: always